# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: 'jakarta.enterprise:jakarta.enterprise.cdi-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.inject:jakarta.inject-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.servlet:jakarta.servlet-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'org.jboss:jboss-ejb-client'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
    open-pull-requests-limit: 10
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "4.x"
    ignore:
      - dependency-name: 'jakarta.ejb:jakarta.ejb-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.enterprise:jakarta.enterprise.cdi-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.inject:jakarta.inject-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'jakarta.servlet:jakarta.servlet-api'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'org.jboss:jboss-ejb-client'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'org.jboss.galleon:galleon-maven-plugin'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'org.jboss.logging:jboss-logging'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'org.jboss.msc:jboss-msc'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'org.wildfly.core:*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'org.wildfly.plugins:*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      - dependency-name: 'org.wildfly.security:*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "4.x"
